### ISSUE TITLE
Support NestJS 8.0.0^

### ISSUE THREAD

**Issue by Dragons0458** [HorusGoul/nest-graphql-scalar-adapter#1]
Ey! Nice project! thank you for the effort

Is possible to update your lib for support NestJS 8.0.0^?

Regards!

**Comment by HorusGoul** [comment]
Hey, I'm glad you like the project!

I just added ^8.0.0 to the peer dependencies of the package, so you'll find it in the latest version (1.1.2).

Thank you :smile:
